#!/bin/zsh
menu () {
  typeset m t a;
  m='\033[0;';
  t='\033[0;';
  while { getopts 'm:t:' a } { case $a {
    (m) 
      m+=${${${${OPTARG//[^0-7iIbB]/}//(#m)[0-7]/3${MATCH};}//[iI]/7;}//[bB]/1;};;
    (t)
      t+=${${${${OPTARG//[^0-7iIbB]/}//(#m)[0-7]/3${MATCH};}//[iI]/7;}//[bB]/1;};;
  }; };
  m=${m%?}m;
  t=${t%?}m;
  for a ( ${@[OPTIND,-1]} ) { printf '\t%b%s\t\t%b%s%b\n' ${m} ${a%% *} ${t} "${a#* }" '\033[0m' };
  # for a ( ${(qq)@[OPTIND,-1]} ) { printf '\t%b%s\t\t%b%s%b\n' ${m} ${${(z)a}[1]} ${t} ${(Q)${(z)a}[2,-1]} '\033[0m' };
}