#!/bin/sh
#
# surf_qsearch:
# Search script for surf. Takes the surf window id as argument.
# POSIX compliant and GNU-free, I think.
#
# Add something like the following to your surf/config.(def.)h, replacing
# surf_qsearch with the name of the file you've copied this code into:
#
# /* Quick searching. */
# #define QSEARCH { \
#     .v = (char *[]){"/bin/sh", "-c", "surf_qsearch $0 $1", winid, NULL } \
# }
#
# Add a keybinding in keys[]:
#
# { MODKEY, GDK_q, spawn, QSEARCH },
#

# Get the full query. The 'echo | dmenu' idiom may be a bit of
# a hack, but it seems to work.
q="$(echo "d\ns\nwe\nwa\nw\nwd\ng\no\ny\ndd\nti\nr\nhj\nl\ni\ni\nsh\nbc" | dmenu)"
[ -z "$q" ] && exit 0

# Extract the engine code.
e="${q%% *}"

# Encode the search string (i.e. the rest of q). xxd was formerly used
# here, but xxd is part of vim packages on some systems, whereas od is
# ubiquitous. A search script that breaks if someone accidentally removes
# vim is stupid.
s=$(printf %s "${q#* }")

case ${e} in
    'd'  ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://duckduckgo.com/?q=${s}";;
    's'  ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://www.startpage.com/do/mypage.pl?prfe=36c84513558a2d34bf0d89ea505333ad761002405484af240c1c89932309a9bc5065027ac0acf304530bea21aa54bdf5?q=${s}";;
    'we' ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://en.wikipedia.org/w/index.php?title=Special%3ASearch&search=${s}";;
    'wa' ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://wiki.archlinux.org/index.php?title=Special%3ASearch&search=${s}";;
    'w'  ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://en.wiktionary.org/w/index.php?search=${s}&go=Go";;
    'wd' ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://de.wiktionary.org/w/index.php?title=Spezial%3ASuche&search=${s}";;
    'g'  ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://github.com/search?utf8=%E2%9C%93&type=&q=${s}";;
    'o'  ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://www.onelook.com/?w=${s}&ls=a";;
    'y'  ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://www.youtube.com/results?search_query=${s}";;
    'dd' ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://www.dict.cc/?s=${s}&=DEEN&=";;
    'ti' ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://tineye.com/search?q=${s}";;
    'r'  ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://www.reddit.com/search?include_over_18=on&q=${s}";;
    'hj' ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://howjsay.com/search?word=aposematism&word=${s}";;
    'l'  ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://www.last.fm/search?q=${s}";;
    'i'  ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://www.imdb.com/find?ref_=nv_sr_fn&q=${s}&s=all";;
    'sh' ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://sci-hub.tw/${s}";;
    'bc' ) xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://bandcamp.com/search?q=${s}";;
    'mal') xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://myanimelist.net/search/?all&q=%{s}";;
    *    ) exit 1;;
esac
