#!/bin/sh
cz() {
local n=0;
local o c w;
while getopts 'nh' o; do 
    case $o in 
        n) n=1;;
        h) ;&
        *)
less -F <<HEREDOC
NAME
    cz - filesystem navigator

SYNOPSIS
    cz [-n]

DESCRIPTION
    Browse the filesystem from current working directory. Parent directory is always first 
    item, the rest are directory present in the current directory. Use -n to surpress listing 
    of all directories and files in the terminal.

BUGS
    Please report any aberrant behavior or bugs to vlg@tutamail.com


HEREDOC
return 1;; esac; done;

until [[ -n $w ]]; do w=$(xwininfo -name 'cz' -int | perl -ne 's/.*?Window id: ([0-9]+) ".*$/$1/ && print') 2>/dev/null; done;

if [ $n -eq 0 ]; then
    while true; do 
        clear; echo ''; lsd -a
        c="$(ls -ap | sed -r '/[^/]$/d; /^\.\/$/d' | dmenu -i -w $w -p "$(pwd)")" || break; cd $c;
    done
else
    while true; do
        c="$(ls -ap | sed -r '/[^/]$/d; /^\.\/$/d' | dmenu -i -w $w -p "$(pwd)")" || break; cd $c;
    done
fi;
}