#!/bin/sh
cz() {
local n=0;
local o c w;
while getopts 'nh' o; do 
    case $o in 
        n) n=1;;
        h) ;&
        *)
less -F <<HEREDOC
NAME
    cz - filesystem navigator

SYNOPSIS
    cz [-n]

DESCRIPTION
    Browse the filesystem from current working directory. Parent directory is always first 
    item, the rest are directory present in the current directory. Use -n to surpress 
    listing of files in the terminal.

BUGS
    Please report any aberrant behavior or bugs to vlg@tutamail.com


HEREDOC
return 1;; esac; done;

until [[ -n $w ]]; do w=$(xwininfo -name 'cz' -int | perl -ne 's/.*?Window id: ([0-9]+) ".*$/$1/ && print') 2>/dev/null; done;

# if which fd; then
#     alias cmd="fd -uu -i -t d -d 1"
# else
    alias cmd="ls -ap | sed -r '/[^/]$/d; /^\.\/$/d'";
# fi

if [ $n -eq 0 ]; then
    while true; do 
        clear; printf '\n'; lsd -a;
        # c="$(cmd | dmenu -i -w $w -p "$(pwd)")" || break; [ -d $c ] && cd $c;
        c="$(cmd | slmenu -i -p "$(pwd)")" || break;
        [ -d $c ] && cd $c;
    done
    clear
else
    while true; do
        clear;
        # c="$(cmd | dmenu -i -w $w -p "$(pwd)")" || break; [ -d $c ] && cd $c;
        c="$(cmd | slmenu -i -p "$(pwd)")" || break;
        [ -d $c ] && cd $c;
    done
fi;
unalias cmd
}