#!/bin/sh
function net () {
rm -rf /run/wpa_supplicant/wlp3s0;
pk wpa_supplicant;
pk sdhcp;
sleep 5;
wpa_supplicant -B -i wlp3s0 -c /etc/wpa_supplicant/wpa_supplicant-wlp3s0.conf -P /tmp/wpa_supplicant;
sdhcp wlp3s0;
}
