#!/bin/zsh
# pape setter
function pape () {
a=( # feh bg options
  '--bg-center'
  '--bg-fill'
  '--bg-max'
  '--bg-scale'
  '--bg-tile'
);
c=~/im; # starting dir & file/folder choice
cd ${c};
until [[ -n ${w} ]]; do; w=$(xwininfo -name 'pape' -int | perl -ne 's/.*?Window id: ([0-9]+) ".*$/$1/ && print') 2>/dev/null; done;
while [[ '' != ${c} ]]; do;
    [ -d ${c} ] && f=($(ls -ap ${c} | grep -v '/')) && d=($(ls -ap ${c} | grep '/' | grep -v '^\./'));
    # c=$(printf "%s\n" "${d[@]}" "${f[@]}" "FEH BG OPTION" | tr -s '\n' | dmenu -i -l $((${#d} + ${#f} + 1)) -p $(pwd)) || return 0;
    c=$(printf "%s\n" "${d[@]}" "${f[@]}" "FEH BG OPTION" | tr -s '\n' | dmenu -i -l $(zcalc -e 'min(16, ${#d} + ${#f} + 1)') -p $(pwd) -w ${w} );
    [ -d ${c} ] && cd ${c} && c=.;
    [ -f ${c} ] && feh ${s-${a[4]}} ${c} || break;
    # [[ ${c} = "FEH BG OPTION" ]] && s=$(printf "%s\n" "${a[@]}" | tr -s '\n' | dmenu -i -l ${#a} -p 'bg image options') && feh ${s} $(perl -ne "s/^.*?'(.*)'/\1/ && print" ~/.fehbg);
    [[ ${c} = "FEH BG OPTION" ]] && s=$(printf "%s\n" "${a[@]}" | tr -s '\n' | dmenu -i -l ${#a} -p 'bg image options' -w ${w}) && feh ${s} $(perl -ne 's/.* [[:punct:]](.+)[[:punct:]]/$1/ && print' ~/.fehbg);
done
unset c a f s d w;
}
# use terminal window rather than top bar, 
# 16 entries at a time
# perl -ne 's/.*?Window id: ([0-9]+) ".*$/$1/ && print'
# sed -nr 's/.*?Window id: ([0-9]+) ".*$/\1/p'