#!/bin/zsh
pape() {
local a s c f d;
a=(--bg-center --bg-fill --bg-max --bg-scale --bg-tile);
setopt nonomatch;
c=~/im/wp; # starting directory
cd $c;
while true; do 
  # [[ -d $c ]] && { f=($(ls -ap $c | pcre2grep -v '/')); d=($(ls -ap $c | pcre2grep '/' | pcre2grep -v '^\./')) };
  [[ -d $c ]] && { f=(*(D-^/)); [[ $f[1] = '*(D-^/)' ]] && f[1]=(); d=(*(D-/)); [[ $d[1] = '*(D-/)' ]] && d[1]=(); } ;
  c=$(printf '%s\n' .. $d %f opts rand slide | fzy -l $((LINES-1)) -p "$(pwd) ") || break;
  if [[ -d $c ]]; then cd $c; c=.;
  elif [[ -f $c ]]; then feh ${s:-${a[4]}} $c || break;
  elif [[ $c = opts ]]; then s=$(fzy -p 'options ' <<< ${(F)a}) && feh ${s:-${a[4]}} "$(pcre2grep -o1 "'(.*)'" ~/.fehbg)";
  elif [[ $c = rand ]]; then feh ${s:-${a[4]}} ${f[RANDOM % $#f + 1]} || break;
  elif [[ $c = slide ]]; then while true; do feh ${s:-${a[4]}} ${f[RANDOM % $#f + 1]}; sleep .75; done;
  fi;
done;
setopt nomatch;
}
