#!/bin/zsh
rdd1() {
  ((# == 0)) && printf '%s\n' 'rdd1: Turns a directory of alba into directories of artists filled with directories of alba in "Artist/Artist [Album (Date)]" format.' && return 1;
  ((# == 1)) && [[ -d $1 ]] && cd $1;
  typeset f d s z x;
  f=(*(/DN)); ((${#f} == 0)) && return 1;

  for d ( $f ) {
    [[ $d =~ '^.+? \[+*? \([\d-]+\)\]$' ]] && continue;
    s=($d/**/*.mp3); ((${#s} == 0)) && continue;
    x="$(mp3info2 -D -p '%a [%l (%y)]' $s[1])";
    [[ -z $x ]] && return 11 || mkdir $x;
    for z ( $s ) { mv $z $x };
    mv $d/**/*.{jpg,png,jpeg,pdf}(.DN) $x 2>/dev/null;
    rmdir $d;
  };

  f=(*(/DN)); ((${#f} != 0)) || return 1;
  for d ( $f ) {
    s=${d%% \[*}; [[ -n $s ]] || return 13;
    [[ -d $s ]] || mkdir $s;
    mv $d $s;
  };
}
