#!/bin/zsh
# DIR OF ALL MP3S, -> DIR OF ARTIST/ALBA/MP3S
t=$(mktemp /tmp/XXXXXX);
ls *mp3 > ${t};
while IFS= read -r m; do;
  z="$(mp3info2 -D -p '%a [%l (%y)]' ${m})";
  mkdir -p ${z};
  zmv ${m} ${z};
done < ${t};

ls . > ${t};
while IFS= read -r d; do;
  mkdir -p ${d%% \[*};
  zmv ${d} ${d%% \[*};
done < ${t};
