#!/bin/zsh
# DIR OF ALL MP3S, -> DIR OF ARTIST/ALBA/MP3S
function rdd2() {
local t=$(mktemp /tmp/rdd2.XXXXXXXX);
local z d m;
ls *mp3 > ${t};
if ! [ -s ${t} ]; then printf "No .mp3's found!"; return 1; fi;
while IFS= read -r m; do;
  z="$(mp3info2 -D -p '%a [%l (%y)]' ${m})";
  mkdir -p ${z};
  zmv ${m} ${z};
done < ${t};

ls . > ${t};
while IFS= read -r d; do;
  mkdir -p ${d%% \[*};
  zmv ${d} ${d%% \[*};
done < ${t};
}