#!/bin/zsh
rndpape () {
  emulate -LR zsh;
  setopt extended_glob;
  typeset -a a;
  typeset -i s;
  typeset d;
  a=(~/im/wp/**/*(.-DN));
  s=${#a};
  d=$(pcre2grep -o1 'feh --no-fehbg (\S+)' ~/.fehbg);
  until { [[ $(read -seq) == y ]] } { feh ${d} ${a[((RANDOM % s + 1))]} };
}
