#!/bin/zsh
function rndpape () {
  setopt extended_glob;
  typeset -a a;
  typeset -i s;
  a=(${(@f)"$(printf '%s\n' ~/im/wp/**/*(.D))"});
  s=$#a;
  while { true } { feh $(pcre2grep -o1 'feh --no-fehbg (\S+) ' ~/.fehbg) ${a[((RANDOM % s + 1))]}; [[ $(read -seq) = y ]] && break };
}
