#!/bin/zsh
# -l LIST | -p PLAYLIST | -a ALBUM | -aa ALL_ALBUMS | -u USERNAME)
# s=$(printf '%s' $a | awk -F/ '{ print $4 }')
# [ $s = 'artist' ] && s='aa' || s=${(M)s#?};
function sptdl () {
cd ~/nm;
local a s d;

[ $# -gt 0 ] && for a in "$@"; do 
  if [[ $a =~ 'playlist' ]]; then s=p;
  elif [[ $a =~ 'album' ]]; then s=a; 
  else return 33; fi;
  spotdl -$s $a || return 1;
  spotdl -l "$(ls -c *.txt)" || return 2;
  rm "$(ls -c *.txt)";
done && return 0;

while IFS= read -r a; do
  if [[ $a =~ 'playlist' ]]; then s=p;
  elif [[ $a =~ 'album' ]]; then s=a;
  else return 3; fi;
  spotdl -$s $a || return 1;
  spotdl -l "$(ls -c *.txt)" || return 2;
  rm "$(ls -c *.txt)";
  printf '%s\n' $a >> ~/nm/spold && sed -i '1,1d' ~/nm/spnew;
done < ~/nm/spnew;
}