#!/bin/zsh
# TAG SHIT DOWNLOADED WITH youtube-dl -o '.../%(artist)s [%(album)s #%(track_number)s (%(upload_date)s)] %(track)s.%(ext)s'
# NO BACKSLASHES
function tagme () {
  if [[ ! -z $1 ]]; then;
    find $1 -name '*.mp3' -type f > /tmp/z;
  else;
    find . -name '*.mp3' -type f > /tmp/z;
  fi;
  while IFS= read -r z; do;
    # mp3info2 \
    #   -C id3v2_fix_encoding_on_write=1 -u2R \
    #   -C write_v24=1 \
    #   -t ${${z##* \#[0-9](#c1,) \([0-9](#c8)\)\] }%.mp3} \
    #   -a ${${${z##*/}% \[*?(\[*\]) \#[0-9](#c1,) \([0-9](#c8)\)\]*}#*/} \
    #   -l ${${z/*([*])* \[/}/ \#[0-9](#c1,) \([0-9](#c8)\)\]*} \
    #   -y ${(M)z/* \((#b)([0-9](#c4))(#b)([0-9](#c2))(#b)([0-9](#c2))\)\] */${match[1]}-${match[2]}-${match[3]}} \
    #   -n ${(M)z/* \#(#b)([0-9](#c1,)) \([0-9](#c8)\)\] */${match[1]}} \
    #   -g "$(cat /tmp/x)" \
    #   -F TPE2=%a \
    #   ${z};
    tageditor set \
      --id3v2-version=4 \
      --force-rewrite \
      --encoding=utf8 \
      --values \
      title=${${z##* \#[0-9](#c1,) \([0-9](#c8)\)\] }%.mp3} \
      artist=${${${z##*/}% \[*?(\[*\]) \#[0-9](#c1,) \([0-9](#c8)\)\]*}#*/} \
      album=${${z/*([*])* \[/}/ \#[0-9](#c1,) \([0-9](#c8)\)\]*} \
      year=${(M)z/* \((#b)([0-9](#c4))(#b)([0-9](#c2))(#b)([0-9](#c2))\)\] */${match[1]}-${match[2]}-${match[3]}} \
      recorddate=${(M)z/* \((#b)([0-9](#c4))(#b)([0-9](#c2))(#b)([0-9](#c2))\)\] */${match[1]}-${match[2]}-${match[3]}} \
      track=${(M)z/* \#(#b)([0-9](#c1,)) \([0-9](#c8)\)\] */${match[1]}} \
      genre="$(cat /tmp/x)" \
      albumartist=${${${z##*/}% \[*?(\[*\]) \#[0-9](#c1,) \([0-9](#c8)\)\]*}#*/} \
      --files ${z};
  done < /tmp/z;
  # rm -f **/*bak;
  # echo "$(fd 'bak$' ${1:-.})" > /tmp/z; 
  # while IFS= read -r f; do rm -f ${f}; done < /tmp/z;
}
