#!/bin/zsh
# tag shit downloaded with youtube-dl -o '.../%(artist)s [%(album)s #%(track_number)s (%(upload_date)s)] %(track)s.%(ext)s'
function tagme () {
local o t z a;
while getopts '' o; do case $o in (*) 
less -F <<HEREDOC
NAME
    tagme - tag audio files.

SYNOPSIS
    tagme [dir(s)]

DESCRIPTION
    Uses tageditor or mp3info2 to tag .mp3's (format can be expanded) files that have been 
    named in format 'ARTIST [ALBUM #TRACK (RELEASEDATE)] TITLE'. Makes use of zsh's parameter 
    expansion, though this could be done with sed, perl, pcregrep, etc, too.
    
EXAMPLES
    tagme
        Tags .mp3 files in current working directory.

    tagme dir1 dir2
        Tags .mp3 files in dir1 and dir2.
    
BUGS
    Please report any aberrant behavior or bugs to vlg@tutamail.com


HEREDOC
return 1;; esac; done;

t=$(mktemp /tmp/tagme.XXXXXXXX);
if (($# > 0)); then
  for o in $@; do ls -UN1 $o/*.mp3 >> $t || return 0; done;
else
  ls -UN1 *.mp3 > $t || return 1;
fi;
(($(wc -l < $t) == 0)) && return 1;

(($(sed -r 's/ \[.*//' $t | sort -u | wc -l) > 1)) && [ "$(printf "2 No\\n1 Yes" | dmenu -i -p "Rename album artist to Various Artists?" -l 2)" = "1 Yes" ] && a="Various Artists" || a=$(sed -r 's/ \[.*//' $t | sort -u | head -1);

# if which tageditor &>/dev/null; then
  while IFS= read -r z; do
    tageditor set \
      --id3v2-version=4 \
      --force-rewrite \
      --encoding=utf8 \
      --values \
        title="${${z##* \#[0-9](#c1,) \([0-9](#c8)\)\] }%.mp3}" \
        artist="${${${z##*/}% \[*?(\[*\]) \#[0-9](#c1,) \([0-9](#c8)\)\]*}#*/}" \
        album="${${z/*([*])* \[/}/ \#[0-9](#c1,) \([0-9](#c8)\)\]*}" \
        year="${(M)z/* \((#b)([0-9](#c4))(#b)([0-9](#c2))(#b)([0-9](#c2))\)\] */${match[1]}-${match[2]}-${match[3]}}" \
        recorddate="${(M)z/* \((#b)([0-9](#c4))(#b)([0-9](#c2))(#b)([0-9](#c2))\)\] */${match[1]}-${match[2]}-${match[3]}}" \
        track=${(M)z/* \#(#b)([0-9](#c1,)) \([0-9](#c8)\)\] */${match[1]}} \
        genre="${(Cj.;.)${(f)"$(</tmp/genre)"}//-/ }" \
        albumartist="$a" \
      --files $z;
  done < $t;
  for o in $@; do rm -f $o/**/*.bak; done;
# elif which mp3info2 &>/dev/null; then
  # while IFS= read -r z; do
  #   mp3info2 \
  #     -C id3v2_fix_encoding_on_write=1 \
  #     -u2R \
  #     -C write_v24=1 \
  #     -t "${${z##* \#[0-9](#c1,) \([0-9](#c8)\)\] }%.mp3}" \
  #     -a "${${${z##*/}% \[*?(\[*\]) \#[0-9](#c1,) \([0-9](#c8)\)\]*}#*/}" \
  #     -l "${${z/*([*])* \[/}/ \#[0-9](#c1,) \([0-9](#c8)\)\]*}" \
  #     -y "${(M)z/* \((#b)([0-9](#c4))(#b)([0-9](#c2))(#b)([0-9](#c2))\)\] */${match[1]}-${match[2]}-${match[3]}}" \
  #     -n "${(M)z/* \#(#b)([0-9](#c1,)) \([0-9](#c8)\)\] */${match[1]}}" \
  #     -g "${(Cj.;.)${(f)"$(</tmp/genre)"}//-/ }" \
  #     -F TPE2="$a" \
  #     $z;
  # done < $t;
# else; return 69; fi;
rm $t;
}
