#!/bin/zsh
# terminal streaming
function twitch () {
while getopts 'f:' o; do
  case ${o} in
    'f') fuck=${OPTARG};;
    *) return 1;;
  esac
done
shift ${OPTIND}-1
mpv \
  --profile=low-latency \
  --ytdl-raw-options=format=${fuck:-'best[height<=360]'} \
  $1
}

