#!/bin/zsh
function uhosts () {
mkdir -p /tmp/h; cd /tmp/h;
# main- ads, spam, scam
xbps-fetch http://winhelp2002.mvps.org/hosts.txt
# jewos
xbps-fetch -o $RANDOM https://github.com/adversarialtools/apple-telemetry/raw/master/blacklist
xbps-fetch -o $RANDOM https://raw.githubusercontent.com/c-edw/ios-telemetry/master/blacklist
# jewsoft
xbps-fetch -o $RANDOM https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/microsoft/all
# jewbook
xbps-fetch -o $RANDOM https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt
xbps-fetch -o $RANDOM https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/facebook/all
# jewgle
xbps-fetch -o $RANDOM https://github.com/nickspaargaren/pihole-google/raw/master/categories/analytics.txt
xbps-fetch -o $RANDOM https://github.com/nickspaargaren/pihole-google/raw/master/categories/android.txt
xbps-fetch -o $RANDOM https://github.com/nickspaargaren/pihole-google/raw/master/categories/dns.txt
xbps-fetch -o $RANDOM https://github.com/nickspaargaren/pihole-google/raw/master/categories/domains.txt
xbps-fetch -o $RANDOM https://github.com/nickspaargaren/pihole-google/raw/master/categories/doubleclick.txt
xbps-fetch -o $RANDOM https://github.com/nickspaargaren/pihole-google/raw/master/categories/firebase.txt
xbps-fetch -o $RANDOM https://github.com/nickspaargaren/pihole-google/raw/master/categories/fonts.txt
xbps-fetch -o $RANDOM https://github.com/nickspaargaren/pihole-google/raw/master/categories/general.txt
xbps-fetch -o $RANDOM https://github.com/nickspaargaren/pihole-google/raw/master/categories/mail.txt
xbps-fetch -o $RANDOM https://github.com/nickspaargaren/pihole-google/raw/master/categories/products.txt
xbps-fetch -o $RANDOM https://github.com/nickspaargaren/pihole-google/raw/master/categories/proxies.txt
xbps-fetch -o $RANDOM https://github.com/nickspaargaren/pihole-google/raw/master/categories/shortlinks.txt
xbps-fetch -o $RANDOM https://github.com/nickspaargaren/pihole-google/raw/master/categories/youtube.txt
xbps-fetch -o $RANDOM https://raw.githubusercontent.com/nickspaargaren/pihole-google/master/google-domains
# https://github.com/notracking/hosts-blocklists
xbps-fetch -o $RANDOM https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt

cat * >> tmp
sed -r '
  /localhost/d;
  /^#+\s*[^0]/d;
  s/^#+ ?[0.]{7}/0.0.0.0 /;
  s/^[^:#0\s]/0.0.0.0 &/;
  s/(^#)([a-zA-Z0-9. ]+)/0.0.0.0 \2/;
  /^#/d;
  s/^[a-zA-Z1-9]+/0.0.0.0 &/;
  s/  +/ /g;
  s/:::+/::/;
  /^0.0.0.0 [a-zA-Z0-9 ]+$/d;
  ' tmp | sort -u > h

# retain commented out addresses
gre '^#' /etc/hosts | sed 's/^#//' > holdme

# comment retained  addresses
while IFS= read -r h; do
  /bin/sed -r --in-place=bak "s/^${h}$/#&/" h;
done < holdme;


# add localhost at top
# sed '1i\
# 127.0.0.1    localhost
# ::1          localhost' h > /etc/hosts;
echo -n '127.0.0.1    localhost
::1          localhost' > /etc/hosts;
cat h >> /etc/hosts;

cd /tmp; rm -r /tmp/h;
}
