#!/bin/zsh
# UPDATE /ETC/HOSTS
function uhosts () {
mkdir -p /tmp/hosts; cd /tmp/hosts;
a=(
  "http://winhelp2002.mvps.org/hosts.txt"
  "https://github.com/adversarialtools/apple-telemetry/raw/master/blacklist"
  "https://raw.githubusercontent.com/c-edw/ios-telemetry/master/blacklist"
  "https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/microsoft/all"
  "https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt"
  "https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/facebook/all"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/analytics.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/android.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/dns.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/domains.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/doubleclick.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/firebase.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/fonts.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/general.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/mail.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/products.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/proxies.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/shortlinks.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/youtube.txt"
  "https://raw.githubusercontent.com/nickspaargaren/pihole-google/master/google-domains"
  "https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt"
  "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-social/hosts"
);

for s in {1..${#a}}; do wget -O ${s} ${a[s]}; done;

cat /tmp/hosts/* ~/dcs/blockme >> tmp;
sed -r '
  /localhost|loopback|ip6-|broadcasthost|local$/d; /^\s+$/d;
  s/  +/ /g; /^ /d;
  /^#{2,}/d; /^\s+#/d; /^\s+$/d;
  s/^# *(0.){3}0/0.0.0.0/;
  s/^[^:#0 ]/0.0.0.0 &/; /^#/d; /^ +#$/d;
  /0.courier-push-apple.com.akadns.net/d; /0-courier.push.apple.com/d;
  s/:::+[^ ]+/::1/;
  /^0.0.0.0 [a-zA-Z0-9 ]+$/d;
  ' tmp | sort -u > h;

gre '^#' /etc/hosts | sed 's/#//' > holdme;

while IFS= read -r h; do
  /bin/sed -r --in-place=bak "s/^${h}$/#&/" h;
done < holdme;

head -29 22 | tail -14 > /etc/hosts;
cat h >> /etc/hosts;

cd ~; rm -rf /tmp/hosts;
}
