#!/bin/zsh
# UPDATE /ETC/HOSTS
function uhosts () {
mkdir -p /tmp/hosts; cd /tmp/hosts;
a=(
  "http://winhelp2002.mvps.org/hosts.txt"
  "https://github.com/adversarialtools/apple-telemetry/raw/master/blacklist"
  "https://raw.githubusercontent.com/c-edw/ios-telemetry/master/blacklist"
  "https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/microsoft/all"
  "https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt"
  "https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/facebook/all"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/analytics.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/android.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/dns.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/domains.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/doubleclick.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/firebase.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/fonts.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/general.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/mail.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/products.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/proxies.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/shortlinks.txt"
  "https://github.com/nickspaargaren/pihole-google/raw/master/categories/youtube.txt"
  "https://raw.githubusercontent.com/nickspaargaren/pihole-google/master/google-domains"
  "https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt"
  "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-social/hosts"
);

for s in {1..${#a}}; do wget -O ${s} ${a[s]}; done;

# https://unix.stackexchange.com/questions/29724/how-to-properly-collect-an-array-of-lines-in-zsh
q=("${(@f)$(perl -ne 's/^#(?:0\.0\.0\.0|::) // && print' /etc/hosts)}");

head -29 22 | tail -14 > /etc/hosts;

/bin/sed -i '1,40d' 22;

cat /tmp/hosts/[0-9]* ~/dcs/blockme | perl -pe "
  s/.*\b((local|broadcast)host|loopback|ip6-\w+)\b.*//n; 
  s/[\ \t\f\r]+/ /g;
  s/^ / /;
  s/#+/#/g;
  s/^:{3,}/::/;
  s/^# ?(0\.0\.0\.0)/0.0.0.0/n;
  s/^# ?(::)/::/n;
  s/^(\s+)?#.*$//;
  s/(^[^0:][^.:])/0.0.0.0 $1/;
  # s/(^[^0]|[^:][^.]|[^:][^ ]|[^0])/0.0.0.0 $1/;
  # s/^ ?([a-zA-Z0-9 /.-]+)$/0.0.0.0 $1/;
  s/(^[^:]\.[^0]+?)/0.0.0.0 $1/;
  s/^ #.*//;
  s/ $//;
" | tr -s '\n' | sort -u > h;

# if [ -s holdme ]; then; 
#   while IFS= read -r h; do perl -ie "s/^${h}$/#&/" h >> /etc/hosts; done < holdme;
# else; cat h >> /etc/hosts; fi;
# for a in {1..${#q}}; do; perl -pe "s/(.*\b${q[a]}$)/#$1/" -i h
[[ -n $q ]] && for a in {1..${#q}}; do; /bin/sed -ir "s/.* ${q[a]}$/#&/" h; done;
cat h >> /etc/hosts;

cd ~; rm -rf /tmp/hosts;
unset a;
}
