#!/bin/zsh
unicode () {
  typeset q;
  FZF_DEFAULT_OPTS="-i -m --reverse --bind=alt-\[:preview-up,alt-\':preview-down,\[:up,\':down";
  q=$(fzf --print-query --preview="uni -q -f '%(char)' search {q} | column" --preview-window=99%:down:sharp <<< '');
  [[ -n $q ]] && uni -q -f '%(char)' search ${q} | fzf -i -m --reverse --border=horizontal --bind=\[:up,\':down;
}
