#!/bin/zsh
uriencode () {
	emulate -LR zsh;
	setopt extendedglob;
	typeset q;
	((# + 1 > OPTIND)) || { q=$(mktemp); while { read -e -t 1 -r } { } > ${q}; [[ -s ${q} ]] || { rm -f ${q}; return } };
	# https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier
	# RFC 3986 section 2.3 Unreserved Characters (January 2005)
	printf '%s' ${(j..)${(s..)@:-${(s..)$(<${q})}}/(#b)([^A-Za-z0-9-_.~])/%${(l.2..0.)$(([##16]#match))}}; rm -f ${q};
}
