#!/bin/zsh
function wic () {
local a;
if ! ps -C wicd &> /dev/null; then;
    echo 'wicd not running!';
elif [ -z ${1} ]; then; 
    echo 'SSID needed!';
elif ! a=$(wicd-cli -yxSl | gre ${1} | pre -o '^[0-9]+'); then;    
    echo 'SSID not found!';
else; 
    wicd-cli -ycn ${a};
fi;
}