#!/bin/zsh
# DOWNLOADS FROM LIST OR, GIVEN A NEW LINK, SCRAPES ALBA FROM EMBEDDED PLAYER AND DIRECT LINKS RELEASES TO LIST
function xrp () {
  cd ~/nm;
  while IFS= read -r a; do;
  if [[ ! -z $1 ]]; then; xrpp $1; fi;
    t1=$(mktemp /tmp/XXXXXX); t2=$(mktemp /tmp/XXXXXX); t3=$(mktemp /tmp/XXXXXX);
    curl ${a} > ${t1};
    # DETECT RIDIRECTION ATTEMPS
    grep 'redirected' ${t1} >& /dev/null && echo ${a} >> ~/nm/redir && sed -i '1,1d' ~/nm/newlinks && break;
    # PENDING RELEASE?
    sed -n '15,/">/p' ${t1} > ${t2};
    # TAGS ON PAGE
    grep 'class="tag"' ${t1} | /bin/grep -Po 'tag/[a-z-]+' | cut -c 5- | /bin/sed -r 's/(^|-)([a-z])/\U\0/g; s/-/ /g' | awk -vRS='\n' -vORS=';' '1' > /tmp/x;

    grep 'releases' ${t2} && echo ${a} >> ~/nm/soon && sort -uo ~/nm/soon ~/nm/soon || (
      # DOWNLOAD ALBUM
      # bcdl ${a};
      youtube-dl \
        --ignore-config \
        --retries 64 \
        --fragment-retries 256 \
        --format mp3 \
        --embed-thumbnail \
        --output '~/nm/%(artist)s [%(album)s #%(track_number)s (%(upload_date)s)] %(track)s.%(ext)s' ${a};
      # MISSING TRACKS?
      (( $(sed -rn '/^[1-9]+\.\ /p' ${t2} | tail -1 | /bin/grep -Po '^\d+') > $(ls *mp3 | wc -l) )) && echo ${a} >> ~/nm/missing && sort -uo ~/nm/missing ~/nm/missing;
      # to-be-created dir(s)
      echo "$(ls *.mp3 | /bin/grep -Po '^.*\(\d{8}\)]' | sed -r 's/( #[0-9NA]+)( \([0-9]{4})([0-9]{2})([0-9]{2}\)\])/\2-\3-\4/')" > ${t3};
      # FIXME figure out when v.a., feat., etc. -> TPE2
      # CREATE DIR `ARTIST [ALBUM (YYYY-MM-DD)]`, PUT MP3S INSIDE, TAG 'EM, (CREATE `ARTIST`), AND PUT IN DIR `ARTIST`
      while IFS= read -r s; do;
        mkdir -p ${s}; /bin/mv *mp3 ${s}; tagme ${s}; mkdir -p ${s%% \[*}; /bin/mv ${s} ${s%% \[*}; break;
      done < ${t3} | sort -u;
      # remove release from list after completion of process so interrupts possibles; remove blank lines from newlinks
      echo ${a} >> ~/nm/oldlinks && sort -uo ~/nm/oldlinks ~/nm/oldlinks;
      echo "\n\n";
    );
    /bin/sed -i '1,1d' ~/nm/newlinks;
  done < ~/nm/newlinks;
  rm ${t1} ${t2} ${t3};
}