#!/bin/zsh
# DOWNLOADS FROM LIST OR, GIVEN A NEW LINK, SCRAPES ALBA FROM EMBEDDED PLAYER AND DIRECT LINKS RELEASES TO LIST
function xrp () {
local o a t1 t2 t3 w s d f;
setopt nonomatch;
while getopts '' o; do case $o in (*)
less -F <<HEREDOC
NAME
    xrp - download, tag, and structure alba from list of links.

SYNOPSIS
    xrp
    xrp [URL(s)]

DESCRIPTION
    Downloads .mp3s (can be modified to 'bestaudio', but 128k .mp3 is the standard free for-
    mat), naming them in format 'ARITST [ALBUM #TRACK (RELEASEDATE)] TITLE', and embedding 
    album/track art, puts these files in a directory in the format 'ARITST [ALBUM (RELEASE-
    DATE)]', calls 'tagme' (which then tags them with their respective artist (track-wise), 
    albumartist, album, release date (as state in the bandcamp page), genre (camelcases 
    listed tags in bandcamp page), and track number), puts this directory in a parent direc-
    tory in the format 'ARTIST', removes the processed link and adds it to the list of down-
    loaded alba/tracks. If the album is yet to be released, the link gets added to the list 
    of future releases; if the album is missing some tracks, the link is added to a list of 
    alba missing tracks. Optional argument of website can be added to bypass the scraping 
    step with xrpp.

EXAMPLES
    xrp
        Do everything as per description, with your current bcnew files.

    xrp https://canthisevenbecalledmusic.com/monthly-recommendations-january-2020
        Scrape the website, then do everything as per description with possibly newly ac-
        quired links.
        
BUGS
    Please report any aberrant behavior or bugs to vlg@tutamail.com


HEREDOC
return 1;;esac; done;

if (($# > 0)); then; xrpp $@; fi;
cd ~/nm;

for a in ${(f)"$(< ~/nm/bcnew)"}; do
    t1=$(mktemp /tmp/xrp1.XXXXXXX); t2=$(mktemp /tmp/xrp2.XXXXXXX); t3=$(mktemp /tmp/xrp3.XXXXXXX);
    curl $a > $t1;
    if pcre2grep -q 'redirected' $t1; then
        a=$(pcre2grep -o '"http.*?"' $t1 | tr -d '"');
        curl $a > $t1;
    fi;
    sed -n '15,/">/p' $t1 > $t2;
    pcre2grep -o1 'class="tag" href="http.+?/tag/(.+?)\?from=\S+"' $t1 > /tmp/genre;
    # rymgenre "$(sed -rn '1s/(.*) by (.*), rel.*/\2 \1/p' $t2)" >> /tmp/genre;
    if pcre2grep -q 'releases' $t2; then
        printf "%s\n" $a >> ~/nm/soon;
        sort -uo ~/nm/soon ~/nm/soon;
    else
        youtube-dl \
            --ignore-config \
            --ignore-errors \
            --retries 64 \
            --fragment-retries 64 \
            --audio-format mp3 \
            --audio-quality 0 \
            --embed-thumbnail \
            --output '~/nm/%(artist)s [%(album)s #%(track_number)s (%(upload_date)s)] %(track)s.%(ext)s' $a;
        if w=(*.mp3(.)) && [[ $w[1] = '*.mp3(.)' ]]; then
            printf "%s\n" $a >> ~/nm/missing;
            sort -uo ~/nm/missing ~/nm/missing;
        else
            if (($(pcre2grep -o1 '^(\d+)\.' $t2 | tail -n 1) > ${#w})); then
                printf '%s\n' $a >> ~/nm/missing;
                sort -uo ~/nm/missing ~/nm/missing;
            fi;
            printf '%s\n' $w | sed -r 's/( #[0-9NA]+)( \([0-9]{4})([0-9]{2})([0-9]{2}\)\]).*/\2-\3-\4/' > $t3;
            d=$(sort -u $t3 | wc -l); f=$(wc -l $t3 | pcre2grep -o '^\d+');
            if ((d != 1)); then [[ "$(printf '%s\n' '2 No' '1 Yes' *.mp3(.) | dmenu -i -p "$f tracks, $d artists/dates: rename dirs to Various Artists? " -l $f)" = '1 Yes' ]] && f=$(sed -r 's/^.* \[/Various Artists [/' $t3 | sort -u | head -n 1) || unset f;
            else unset f; fi

            for s in ${(f)"$(sort -u $t3)"}; do
                mkdir -p ${f:-$s};
                mv ${(@f)w} ${f:-$s};
                tagme ${f:-$s};
                mkdir -p ${f%% \[*} 2&>/dev/null && mv $f ${f%% \[*} && unset f || \
                mkdir -p ${s%% \[*} && mv $s ${s%% \[*};
                break;
            done;
        fi;
        printf '%s\n' $a >> ~/nm/bcold && sort -uo ~/nm/bcold ~/nm/bcold; printf '\n================================================================\n';
    fi;
    sed -i '1,1d' ~/nm/bcnew;
    rm -f $t1 $t2 $t3;
done;
rm -f ~/nm/**/*.bak;
}