#! /bin/zsh
# conky dzen2 status bar
FG='#9ffb00'
BG='#202020'
FONT="-*-firacode-medium-r-*-*-14-*-*-*-*-*-*-*"

# Set last set background
~/.fehbg &

# Make sure an instance of Sublime Text 3 is running
subl3 &

# Snowstorm
# pkill xsnow ; xsnow -snowflakes 1000 -santaspeed 15 -santa 1 -santaupdatefactor 1 -notrees -whirl 180 -yspeed 222 -xspeed 88 & disown

# fuck touchpad
pkill --pidfile=/tmp/syndaemon
syndaemon -d -i 131072 -p /tmp/syndaemon

# Screen lock
xautolock -time 20 -secure -locker 'setxkbmap us; export LANG=en_US.UTF-8; xbacklight -set 0; slock; xbacklight -set 15' &

# RHS of status bar
pkill conky
dzen2 -e - -ta r -x '1084' -w '836' -h '16' -fg $FG -bg $BG -fn $FONT < <(conky -d -c ~/.config/conky/conky.conf) &
pgrep pomo && dzen2 -e - -ta l -x '1080' -w '64' -h '16' -fg $FG -bg $BG -fn $FONT < <(/root/.config/zsh/scripts/pomo status) &

# Shortcuts
# pkill xbindkeys
# xbindkeys &

