#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod1    # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier

#hc keybind $Mod-Shift-q quit
hc keybind $Mod-F12                     reload
hc keybind $Mod-Shift-c                 close

hc keybind $Mod-t                       spawn tabbed -p s-1 -dcr 2 st -w ''
hc keybind $Mod-Shift-t                 spawn st
hc keybind $Mod-Escape                  spawn dmenu_run -i

# basic movement
# focusing clients
# hc keybind $Mod-Control-Left  focus left
# hc keybind $Mod-Control-Down  focus down
# hc keybind $Mod-Control-Up    focus up
# hc keybind $Mod-Control-Right focus right

# moving clients
hc keybind $Mod-Left                    shift left
hc keybind $Mod-Down                    shift down
hc keybind $Mod-Up                      shift up
hc keybind $Mod-Right                   shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-Control-Up              split bottom 0.5
hc keybind $Mod-Control-Down            split top 0.5
hc keybind $Mod-Control-Left            split right 0.5
hc keybind $Mod-Control-Right           split left 0.5

# resizing frames
resizestep=0.025
hc keybind $Mod-Shift-Left              resize left +$resizestep
hc keybind $Mod-Shift-Down              resize down +$resizestep
hc keybind $Mod-Shift-Up                resize up +$resizestep
hc keybind $Mod-Shift-Right             resize right +$resizestep

# virtual desktops
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-F$key" use_index "$i"
        hc keybind "$Mod-Shift-F$key" move_index "$i"
    find
done

# DESK CYCLING
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-Shift-r                 remove
hc keybind $Mod-Shift-d                 fullscreen toggle
hc keybind $Mod-Shift-f                 set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-g                 floating toggle
# hc keybind $Mod-p                       pseudotile toggle

# The following cycles through the available layouts within a frame, but skips layouts, if the layout change wouldn't affect the actual window positions. i.e., if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                \
            or , and . compare tags.focus.curframe_wcount = 2        \
                     . cycle_layout +1  max grid vertical horizontal \
               , cycle_layout +1
# mouse
hc mouseunbind --all
hc mousebind $Mod-Shift-Button1         move
hc mousebind $Mod-Shift-Button3         resize

# focus
hc keybind $Mod-Tab                     cycle_all +1
hc keybind $Mod-Shift-Tab               cycle_all -1
hc keybind $Mod-Control-c               cycle

# theme
hc attr theme.tiling.reset              1
hc attr theme.floating.reset            1
hc set frame_border_active_color        '#392030'

# top bar
hc set frame_border_normal_color        '#202020'
hc set frame_bg_normal_color            '#803380'
hc set frame_bg_active_color            '#9FFB00'
hc set frame_border_width               0
hc set always_show_frame                1
hc set frame_bg_transparent             1
hc set frame_transparent_width          1
hc set frame_gap                        0

# inner border active/inactive window ; inner cannot be greater than outer ; virt desktop selection color
hc attr theme.active.color              '#9FFB00'
hc attr theme.normal.color              '#803380'
hc attr theme.urgent.color              '#FF0000'

hc attr theme.border_width              1
hc attr theme.floating.border_width     1

hc attr theme.active.outer_color        '#9FFB00'
hc attr theme.active.inner_color        '#9FFB00'

hc attr theme.inner_width               0
hc attr theme.inner_color               '#202020'

hc attr theme.floating.outer_width      0
hc attr theme.floating.outer_color      '#803380'

hc attr theme.background_color          '#1A1A1A'

hc set window_gap                       1
hc set frame_padding                    0
hc set smart_window_surroundings        off
hc set smart_frame_surroundings         off
hc set mouse_recenter_gap               0

# rules
hc unrule -F
hc rule                                 class='Firefox'     tag=2
hc rule                                 class='tabbedsurf'  tag=2
hc rule                                 class='musescore'   tag=3
hc rule                                 class='qpdfview'    tag=4
hc rule                                 class='Gimp'        tag=3
hc rule                                 class='qBittorrent' tag=9
hc rule                                 class='Nicotine'    tag=9

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# focus new clients?
hc rule focus=on 

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done

# Autorun
[[ -z "$HLWM_LOADED" ]] && sleep 1; ~/.config/herbstluftwm/autorun; ~/.config/zsh/scripts/keys;