#!/bin/zsh
[[ -t 0 ]] || return 1;
# { which zsh && which pup && which curl } &>/dev/null || return 2;
ping -c 1 1.1.1.1 &>/dev/null || return 3;
emulate -LR zsh;
setopt pipe_fail;
typeset query baseurl t n; 
typeset -i pages q c r R x;
typeset -a title url size format bitrate posted hash;
n=$'\n'; t=$(mktemp);
baseurl=http://audiobookbay.nl;
query="${${@}:-$(read -er "?${n}> ")}";
[[ ! ${query} =~ '^\s*$' ]] || return 4;
curl -sfLH User-Agent: ${baseurl}/page/1/'?s='${query// /+} > ${t};

[[ $(pup -f ${t} 'h3 text{}') == 'Not Found' ]] || ((${$(pup -f ${t} -n '.postTitle'):-0} == 0)) && { printf '\nNo results.\n' ${query}; exit 0 };
pages=${${$(pup -f ${t} '.wp-pagenavi a:last-child attr{href}')%/*}#/page/}; 
((pages!=0)) || { printf '\nNo results.\n'; exit 0 };

((pages > 5)) && [[ $(read -seq "?${n}${pages} pages, show all?") == n ]] && {
   read -seq "q?${n}Number of pages from total of ${pages} to show> ";
  ((q > 0 && q <= pages)) && q=pages || q=5;
};

for q ( {1..${pages}} ) {
  title+=(${(fqq)"$(pup -p -f ${t} 'h2 a[href^=/audio-books/] text{}')"});
  url+=(${(fqq)"$(pup -p -f ${t} 'h2 a[href^=/audio-books/] attr{href}')"});
  size+=(${(qq)${(ps.Size: .)"$(pup -p -f ${t} 'p[style=text-align:center;] text{}' | tr -d '\n')"}[2,-1]%%s*});
  format+=(${(fqq)"$(pup -p -f ${t} 'p[style=text-align:center;] span:nth-child(2) text{}')"});
  bitrate+=(${(fqq)"$(pup -p -f ${t} 'p[style=text-align:center;] span:nth-child(3) text{}')"});
  posted+=(${(fqq)"$(pup -p -f ${t} 'p[style=text-align:center;] text{}' | tr -d '\n' | pcre2grep -o1 'Posted:\s*(.+?)Format')"});
  curl -sfLH User-Agent: ${baseurl}/page/$((q+1))/'?'s=${query// /+} > ${t};
};

R=${#title};
r=${(c)#${#title}};
x=$((COLUMNS - r - 2 - 2 - 10 - 2 - 8 - 2 - 3 - 2 - 11));

while { true } {
  c=$(for q ( {1..${R}} ) {
    printf "%.${r}d  %b%-${x}.${x}s  %b%10.10s  %b%8.8s  %b%3.3s  %b%11.11s\n" \
      ${q} \
      '\033[34;1m' ${(Q)title[q]:--} \
      '\033[35;1m' ${(Q)size[q]:--} \
      '\033[37;1m' ${(Q)bitrate[q]:--} \
      '\033[36;1m' ${(Q)format[q]:--} \
      '\033[32;1m' ${(Q)posted[q]:--};
  } | fzy -l $LINES -q "${query}" | cut -f 1 -d ' ') || break;
  ((c > 0 && c < R +1)) && hash+=(${${${"$(curl -sfLH User-Agent: ${baseurl}${(Q)url[c]})"##*Info Hash:</td>}%%</td>*}#*>});
};

((${#hash} > 0)) && { qbittorrent ${(u)hash} &>/dev/null & disown };
rm -f ${t}; return 0;
