#!/bin/zsh

typeset query baseurl t;
integer pages q c r R x;
typeset -a title url size format bitrate posted;
typeset -aU hash;
t=$(mktemp);
baseurl=http://audiobookbay.nl;

((# == 0)) && read -r 'query?> ' || query="$@";
[[ ${query} =~ '^\s*$' ]] && return 1 || query=${query// /+};

curl -sfLH User-Agent: ${baseurl}/page/1/'?s='${query} > ${t};

[[ $(pup -f ${t} 'h3 text{}') = 'Not Found' ]] || ((${$(pup -f ${t} -n '.postTitle'):-0} == 0)) && read -sk1 "?${q}: No results. " && exit 1;
pages=${${$(pup -f ${t} '.wp-pagenavi a:last-child attr{href}')%/*}#/page/}; ((pages==0)) && exit 0

for q in {1..${pages}}; do
  title+=(${(f)"$(pup -f ${t} 'h2 a[href^=/audio-books/] text{}')"});
  url+=(${(f)"$(pup -f ${t} 'h2 a[href^=/audio-books/] attr{href}')"});
  size+=(${(f)"$(pup -f ${t} 'p[style=text-align:center;] text{}' | tr -d '\n' | pcre2grep -o1 'File Size: (\d+(?:\.\d+)? [KMGT]i?B)sP?')"});
  format+=(${(f)"$(pup -f ${t} 'p[style=text-align:center;] span:nth-child(2) text{}')"});
  bitrate+=(${(f)"$(pup -f ${t} 'p[style=text-align:center;] span:nth-child(3) text{}')"});
  posted+=(${(f)"$(pup -f ${t} 'p[style=text-align:center;] text{}' | tr -d '\n' | pcre2grep -o1 'Posted: (.+?)Format')"});
  curl -sfLH User-Agent: ${baseurl}/page/$((q+1))/'?'s=${query} > ${t};
done;
R=${#title};
r=${(c)#${#title}};
x=$((COLUMNS - r - 10 - 8 - 3 - 11 - 10));
while true; do
  c=$(for q in {1..${R}}; do
    printf "%.${r}d  %b%-${x}.${x}s  %b%10.10s  %b%8.8s  %b%3.3s  %b%11.11s\n" $q '\033[1m' ${title[q]} '\033[34;1m' ${size[q]} '\033[32;1m' ${bitrate[q]} '\033[32;0m' ${format[q]} '\033[34m' ${posted[q]};
  done| fzy -l $LINES | cut -f 1 -d ' ');
  ((c > 0)) && ((c < R +1)) && hash+=($(curl -sfLH User-Agent: ${baseurl}${url[c]} | pcre2grep -Mo1 'Info Hash:</td>\n<td>(.+?)</td>')) || break;
done;
if ((${#hash} > 0)); then qbittorrent ${hash} &>/dev/null & disown; fi;
rm ${t};
