#!/bin/zsh
((# == 0)) && return;
typeset a s d q; s=$(mktemp); d=$(mktemp);
for q ( $@ ) {
  a=$(pcre2grep -o1 '(https?://.+\.bandcamp\.com)' <<< $q);
  lynx -listonly -dump "${a}/music" | pcre2grep -o1 '^\s*\d+\.\s+(https?://.+\.bandcamp\.com/(album|track)/\S+)' >> $s;
};
sort -u $s > $d;
diff ~/nm/bcnew $d | pcre2grep -o1 '^> +(.*)$' > $s;
diff ~/nm/bcold $s | pcre2grep -o1 '^> +(.*)$' > $d;
diff ~/nm/soon  $d | pcre2grep -o1 '^> +(.*)$' > $s;
cat ~/nm/bcnew >> $s;
sort -u $s > ~/nm/bcnew;
rm $s $d;
