#!/bin/zsh
# Gives a dmenu prompt to mount disk/drives. If found in /etc/fstab, it'll be mounted; otherwise, you'll be prompted to give a mountpoint from already existing directories. 
# until [[ -n ${w} ]]; do; w=$(xwininfo -name 'dmnt' -int | perl -ne 's/.*?Window id: ([0-9]+) ".*$/$1/ && print') 2>/dev/null; done;
case $(printf "mount\\nunmount" | dmenu -i -p '..?') in
'mount') 
    a=$(lsblk -nlpo 'name,label,type,size,uuid,state,mountpoint' 2>/dev/null | grep -v '/home$|/boot$|/$|SWAP');
    s=$(echo "$(echo ${a} | dmenu -i -p 'mount..?' -l $(echo ${a} | wc -l))" | /bin/grep -oP '^[\w/]+');
    mount ${s} && return 0;
    while [ -n ${c-z} ]; do c="$(echo "$(/bin/ls -ap | /bin/grep -iP "^[\.\w][^\$/]+/$")" | dmenu -i -p "mount where..?")"; cd "${c}"; done;
    yn "Mount ${s} to $(pwd)?" 'mount ${s} "$(pwd)"';;
'unmount') 
    a=$(findmnt --real -nlo 'target,source,fstype');
    umount "$(echo "${a} | dmenu -i -p 'unmount (target, source, fstype)..?')" -l $(echo ${a} | wc -l) | /bin/grep -oP '^[\w/]+')";;
esac;
unset a s c w;