#!/bin/zsh
# Gives a dmenu prompt to mount disk/drives that are not already mounted, not swap, not root, not boot. If found in /etc/fstab, it'll be mounted; otherwise, you'll be prompted to give a mountpoint from already existing directories. 

# until [[ -n ${w} ]]; do; w=$(xwininfo -name 'dmnt' -int | perl -ne 's/.*?Window id: ([0-9]+) ".*$/$1/ && print') 2>/dev/null; done;
case $(printf "mount\numount" | dmenu -i -l 2 -p '?') in
'mount') 
    a=(${(@f)"$(lsblk -nlpo 'name,label,type,size,uuid,state,mountpoint' 2>/dev/null | /bin/grep -Pv '\srunning\s|/boot$|/$|SWAP' | grep -v "${(@F)"$(findmnt --real -nlo 'source')"}" | column)"});
    s=$(printf "%s\n" ${(@)a} | dmenu -i -p 'device  label  type  size  uuid  status  mountpoint' -l ${#a} | awk '{print $1}') || return 1;
    mount ${s} 2&>/dev/null && return 0;
    while true; do c=$(ls -ap | /bin/grep -P '^(?!\./$).+/$' | dmenu -i -p "$(pwd)") || break; cd ${c}; done;
    [ "$(printf "no\\nyes" | dmenu -i -p "mount ${s} to $(pwd)?" -l 2)" = "yes" ] && mount ${s} $(pwd);;
'umount') 
    a=(${(@f)"$(findmnt --real -nlo 'target,source,fstype' | column | tr '\t' '\n')"});
    s=$(printf "%s\n" ${(@)a} | dmenu -i -l ${#a} -p 'target  source  fstype' | /bin/grep -oP '^[\w/]+') || return 1;
    [ "$(printf "no\\nyes" | dmenu -i -p "unmount ${s}?" -l 2)" = "Yes" ] && umount ${s};;
esac;
