#!/bin/sh
if [ $# -eq 1 ]; then b="$1"; 
elif ps -C firefox &>/dev/null; then b=firefox; else b=sf; fi;

url=$(cat ~/.sfeed/feeds.txt | dmenu -l 48 -i | pcre2grep -o1 '(http.*$)')
test -n "$url" && $b "$url"
unset b url