#!/bin/zsh
# pup made interactive
emulate -LR zsh;
FZF_DEFAULT_OPTS="--phony --reverse --print-query --border=horizontal --bind=alt-\':preview-down,alt-\[:preview-up --preview-window=99%:down:sharp";
if [[ -t 0 && ${#} -eq 1 && -s ${1} ]] {
  fzf --preview="pup -p -f ${1:a:q} "{q}"" <<< '';
} else {
  typeset q; q=$(mktemp);
  while { read -e -t 1 -r } { } > ${q} && fzf --preview="pup -p -f ${q} "{q}"" --preview-window=99%:down:sharp <<< '';
  rm ${q};
};
