#!/bin/sh
# This script is called on startup for one-off cmds

# /usr/share/X11/xkb/rules for `-option ""'
setxkbmap -layout "us,bg,de" -variant ",phonetic," -geometry "pc" -option "grp:win_space_toggle" -option caps:super &

# ... delay repeatrate
xset r rate 240 80 &

# Map the caps lock key to super...
# setxkbmap -option caps:super

# But when it is pressed only once, treat it as escape.
pgrep xcape || xcape -e 'Super_L=Escape' &

# Map the menu button to right super as well.
xmodmap -e 'keycode 135 = Super_R' &

# Shortcuts
pgrep xbindkeys || xbindkeys &

# fuck trackpad
pgrep syndaemon || syndaemon -d -i 131072

# Make sure an instance of Sublime Text 3 is running
pgrep subl3 || subl3 &

# Set last set background
~/.fehbg &

# Screen lock
pgrep xautolock || xautolock -time 20 -secure -locker 'setxkbmap us; export LANG=en_US.UTF-8; xbacklight -set 0; slock; xbacklight -set 15' &

# Snowstorm
# pkill xsnow ; xsnow -snowflakes 1000 -santaspeed 15 -santa 1 -santaupdatefactor 1 -notrees -whirl 180 -yspeed 222 -xspeed 88 & disown

# conky dzen2 RHS status bar
FG='#9ffb00'
BG='#202020'
FONT="-otf-fira code-medium-r-*-*-14-*-*-*-*-*-*-*"
pgrep conky && pkill -KILL conky
dzen2 -e - -ta r -x '1084' -w '836' -h '16' -fg $FG -bg $BG -fn $FONT < <(conky -d -c ~/.config/conky/conky.conf) &
pgrep pomo && dzen2 -e - -ta l -x '1080' -w '64' -h '16' -fg $FG -bg $BG -fn $FONT < <(/root/.config/zsh/scripts/pomo status) &
