#!/bin/sh
# This script is called on startup to remap keys.

# /usr/share/X11/xkb/rules for `-option ""'
setxkbmap -layout "us,bg,de" -variant ",phonetic," -geometry "pc" -option "grp:win_space_toggle" -option caps:super &
# Increase key speed via a rate change
xset r rate 250 48 &
# Map the caps lock key to super...
# setxkbmap -option caps:super
# But when it is pressed only once, treat it as escape.
# killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'
pgrep xcape || xcape -e 'Super_L=Escape' &
# Map the menu button to right super as well.
xmodmap -e 'keycode 135 = Super_R' &
# Shortcuts
pgrep xbindkeys || xbindkeys &
