#!/bin/zsh
[ "$(realpath ..)" != '/media/ELEM/Music' ] && printf '/media/ELEM/Music not parent dir!\n' && return 1;
for a in ${(@f)"$(ls . | cut -c 1 | sort -u)"}; do
  [[ -d ../${(U)a} ]] && rsync -vah ${a}* ../${(U)a} || rsync -vah ${a}* ../123 ;
done
sync;
