#!/bin/zsh
# https://raw.githubusercontent.com/tedmiston/zero-noise/master/noise.sh
typeset c o d;
while { getopts c: o } { case ${o} {
  (c) case ${(ML)OPTARG#?} { (w) c=white;; (p) c=pink;; (b) c=brown;; };;
  (*) printf '%s\n' 'Usage:  noise [-c b|B|p|P|w|W*] [^\d+(:\d*){0,2}(\.\d+)?$]'; return 1;;
} };
# [[ ${@[OPTIND]} =~ '^\d+(\:\d*){0,2}(\.\d+)?$' ]] && d=${@[OPTIND]} || d=90:00;
pcre2grep -q '^\d+(\:\d*){0,2}(\.\d+)?$' <<< ${@[OPTIND]} && d=${@[OPTIND]} || d=90:00;
sox -t sw -r 24k -c 2 /dev/zero -t alsa synth ${c:-pink}noise vol -10 dB band -n 800 1200 fade q 5 ${d} 15;
