#!/bin/zsh
# pape setter
a=(
  '--bg-center'
  '--bg-fill'
  '--bg-max'
  '--bg-scale'
  '--bg-tile'
);
c=~/im/wp; # starting dir & file/folder choice
cd $c;
while true; do;
    [ -d $c ] && f=($(ls -ap $c | pcre2grep -v '/')) && d=($(ls -ap $c | pcre2grep '/' | pcre2grep -v '^\./')); 
    c=$(printf "%s\n" "${d[@]}" "${f[@]}" "bgopts" "rand" | dmenu -i -p $(pwd) ) || break; 
    [ -d $c ] && cd $c && c=.;
    [ -f $c ] && (feh ${s-${a[4]}} $c || break);
    [ $c = "bgopts" ] && s=$(printf "%s\n" "${a[@]}" | dmenu -i -p 'bg image options') && feh $s $(pcre2grep -o1 "'(.*)'$" ~/.fehbg &>/dev/null);
    [ $c = "rand" ] && (feh ${s-${a[4]}} $(ls -ap . | pcre2grep -v '/' | shuf -n 1) || break);
done
unset c a f s d;
