#!/bin/zsh
# gen () {
((# == 0)) || return 1;
typeset l u n s e x q a n1 n2 o1 o2; typeset -i length; q=$'\n';

read -r 'length?Length [64]> '; ((length > 0)) || length=64;
l=$([[ $(read -eq "?${q}No lowercase [y/*]?") == y ]] || <<< --lower);
u=$([[ $(read -eq "?${q}No uppercase [y/*]?") == y ]] || <<< --upper);
n=$([[ $(read -eq "?${q}No numbers   [y/*]?") == y ]] || <<< --numeric);
s=$([[ $(read -eq "?${q}No special   [y/*]?") == y ]] || <<< --special);
e=$([[ $(read -eq "?${q}No extended  [y/*]?") == y ]] || <<< --extended);
read -r "x?${q}Exclude>    ";
o2=0;
[[ -z ${x} ]] || x=-x\ ${(j.,.)${(un)${(s..)x}}};

for a ( {1..32} ) {
  n1=$(keepassxc-cli generate --length ${length} ${l} ${u} ${n} ${s} ${e} ${x});
  n2=$(keepassxc-cli estimate ${n1} | awk '{print $4}');
  ((n2 > o2)) && { o2=${n2}; o1=${n1} };
};
printf '%s\n' ${n1};
# }
