#!/bin/sh

xidfile='/tmp/tabbed-surf.xid'

if [ $# -gt 0 ]; then
  uri="$1"
else
  # become new default starting page
  uri='file:///root/.config/startpage/ss1.htm'
fi

xid=$(cat $xidfile) 2>/dev/null
if [ ! -r $xidfile ] || ! xprop -id $xid >/dev/null 2>&1; then 
  tabbed -dn tabbedsurf -r 2 surf -e '' "$uri" > $xidfile 2>/dev/null &
else
  surf -e $xid "$uri" >/dev/null 2>&1 &
fi

unset uri xid