#!/bin/zsh
xidfile='/tmp/tabbed-surf.xid';
((# > 0)) || uri='file:///root/.config/startpage/ss1.htm';
xid=$(<${xidfile}) &>/dev/null;

if { [[ ! -r ${xidfile} ]] || ! xprop -id ${xid} >/dev/null } &>/dev/null {
  for u ( ${uri:-${@}} ) { tabbed -dn tabbedsurf -r 2 surf -e '' "${u}" >${xidfile} &>/dev/null & };
} else {
  for u ( ${uri:-${@}} ) { surf -e ${xid} "$u" &>/dev/null & };
};

unset u uri xid
