#!/bin/zsh
[ $# -eq 0 ] && return 1;
cd ~/mov;
for a in "$@"; do 
  # -l LIST | -p PLAYLIST | -a ALBUM | -aa ALL_ALBUMS | -u USERNAME)
  # s=$(printf '%s' $a | awk -F/ '{ print $4 }')
  # [ $s = 'artist' ] && s='aa' || s=${(M)s#?};
  [[ $a =~ 'playlist' ]] && s=p || [[ $a = 'album' ]] && s=a || return 69;
  spotdl -$s $a;
  spotdl -l *.txt;
  rm *.txt
done;