#!/bin/zsh
emulate -LR zsh;
setopt pipe_fail;
# { which zsh && which surfraw && which rdrview && which elinks && which fzf } &>/dev/null || return 2;
[[ -t 0 ]] || return 1;
typeset elvi cmd;
cmd='elinks -dump -no-numbering -no-references';

elvi=$(fzf -i +m --reverse --border=horizontal < ~/.config/surfraw/cache) || return 1;
fzf --disabled --reverse --border=horizontal --bind=alt-/:toggle-preview,alt-\[:preview-up,alt-\':preview-down --preview="surfraw -escape-url-args=yes -p --  ${elvi} "{q}" | xargs -d '\n' rdrview -B \"${cmd}\" | fmt -w $((COLUMNS*94/100))" --preview-window=99%:down:sharp --header="${(C)elvi}" <<< '';

rm -rf /tmp/*(/L80N) ~/.elinks/cookie*(.N);
