#!/bin/sh
[ $# -eq 0 ] && return 1;
#if ps -C firefox &>/dev/null; then
#  b=firefox;
#elif ps -C surf &>/dev/null; then
#  b=sf;
#else
  b='lynx';
#fi
q=$(surfraw -elvi | tail -n +2 | cut -s -f1 | fzy -l $LINES) || return 1;
surfraw ${q%% *} -browser=$b "$@";

