#!/bin/sh
if ps -C firefox; then
    b='/sbin/firefox';
elif ps -C surf; then
    b="~/.config/zsh/scripts/sf"
else
    b='/sbin/lynx';
fi
q=$(surfraw -elvi | tail -n +2 | cut -s -f1 | dmenu -i) || return 1;
surfraw ${q%% *} -browser="$b" ${q#* }
