#!/bin/zsh
# one-off cmds script called somewhere sometime durring xstart

# only explicit beeps
xset b off &


# mic mute 
amixer sset Capture nocap &


# backlight
xbacklight -set 15 &


# ... delay repeatrate
xset r rate 275 85 &


# /usr/share/X11/xkb/rules for `-option ""'
setxkbmap -layout "us,bg,de" -variant ",phonetic,deadgraveacute" -geometry "pc" -option "grp:win_space_toggle" -option caps:super &


# Map the menu button to right super
xmodmap -e 'keycode 135 = Super_R' &


# Shortcuts
ps -C xbindkeys &>/dev/null || xbindkeys &


# Map the caps lock key to super with single press treated as escape
# setxkbmap -option caps:super
ps -C xcape || xcape -e 'Super_L=Escape' &


# fuck trackpad
ps -C syndaemon &>/dev/null || syndaemon -d -i 131072 &


# Screen lock
ps -C xautolock &>/dev/null || xautolock -time 20 -secure -locker 'xbacklight -set 0; slock; xbacklight -set 15' &


# music 
ps -C mpd &>/dev/null || { mpd; sleep 15; mpdas -d; } &
# ps -C mpdas &>/dev/null || 
# if [[ $(pgrep -xc mpdas) -ne 1 ]]; then pkill -KILL -i -x mpdas; mpdas -d; fi;


#cron
ps -C crond &>/dev/null || crond &


# Snowstorm
# pkill xsnow ; xsnow -snowflakes 1000 -santaspeed 15 -santa 1 -santaupdatefactor 1 -notrees -whirl 180 -yspeed 222 -xspeed 88 & disown


# Set last set background
~/.fehbg &


# ~/src/dwmsss/dwmsss &
slstatus &


# conky dzen2 RHS status bar
# FG='#9ffb00'
# BG='#202020'
# FONT="-otf-fira code-medium-r-*-*-14-*-*-*-*-*-*-*"
# pgrep conky && pkill -KILL conky
# dzen2 -e - -ta r -x '1084' -w '836' -h '16' -fg $FG -bg $BG -fn $FONT < <(conky -d -c ~/.config/conky/conky.conf) &
# pgrep pomo && dzen2 -e - -ta l -x '1080' -w '64' -h '16' -fg $FG -bg $BG -fn $FONT < <(/root/.config/zsh/scripts/pomo status) &
