#!/bin/zsh
# one-off cmds script called somewhere sometime durring xstart



# fuck trackpad
ps -C syndaemon &>/dev/null || syndaemon -d -i 131072 &


# fuck short circuits
xinput --disable  2 & # Virtual Core Pointer
xinput --disable  4 & # Virtual Core XTEST Pointer
xinput --disable 14 & # TPPS/2 IBM TrackPoint
xinput --disable 15 &

xdotool mousemove 1920 1080


# only explicit beeps
xset b off &


# mic mute
amixer sset Capture nocap &


# backlight
xbacklight -set 15 &


# ... delay repeatrate
xset r rate 225 85 &


# /usr/share/X11/xkb/rules for `-option ""'
# setxkbmap -layout "us,bg,de" -variant ",phonetic,deadgraveacute" -geometry "pc" -option "grp:win_space_toggle" &
setxkbmap -layout "us,bg" -variant ",phonetic" -geometry "pc" -option "grp:win_space_toggle" &


# Map the menu button to right super
xmodmap -e 'keycode 135 = Super_R' &


# Shortcuts
ps -C xbindkeys &>/dev/null || xbindkeys &


# Map the caps lock key to super with single press treated as escape
ps -C xcape || xcape -e 'Super_L=Escape' &


# Screen lock
# ps -C xautolock &>/dev/null || xautolock -time 20 -secure -locker 'xbacklight -set 0; slock; xbacklight -set 15' &


# click-clack
# ps -C buckle &>/dev/null || buck 30 &


# Snowstorm
# pc -C xsnow &>/dev/null || xsnow -snowflakes 1000 -santaspeed 15 -santa 1 -santaupdatefactor 1 -notrees -whirl 180 -yspeed 222 -xspeed 88 & disown


# Set last set background
/root/.fehbg &


ps -C scrond &>/dev/null || scrond &


slstatus &
