#!/bin/zsh
ping -c 1 github.com &>/dev/null || return 1;
typeset omdbapikey OSuser OSpass f;
# --addic7ed Auser Apass --legendastv Luser Lpass;
typeset -a open file;
OSuser=VwAxYImyiMgeaXWXOSkB;
OSpass=HgFdrwvpWYhSfSoHZhKcBQVGvimwRrKopFPNEXqWPEBsakGHXTTHgtoweeVXrnFXipDBICGSJeQzircESKtjPKUyBWZjKPBRyQKDVlIkinPrnSGDigJLYMMhGMwFIoS;
omdbapikey=c62d6dc4;

((# == 0)) && {
  open=(${(u)${(f)"$( ps -o cmd -C mpv )"}/(* \/|*)//});
  ((${#open} > 1)) && {
    [[ -t 0 ]] && {
      file=(${(f)"$(fzf -i -m --header='Files to search subs for: ' --reverse --border=horizontal <<< ${(F)files})"}) || return 1;
    } || {
      while { true } { file+=("$(dmenu -p 'Select file to search subs for: ' -l 16 <<< ${(F)files})") || break };
    };
  } || { file=${open[1]} };
} || {
  # file=(${(f)"$(printf '%s\n' ~/mov/**/* | fzf -i -m --header='Files to search subs for: ' --reverse --border=horizontal)"});
  file=(${@:a});
};

for f ( ${file} ) {
  [[ -f ${f} ]] || continue;
  subliminal \
    --opensubtitles ${OSuser} ${OSpass} \
    --omdb ${omdbapikey} \
    download -l en -hi -d ${f:h} ${(qqq)f};
    { kill ${"$(ps -o pid,cmd -C mpv | pcre2grep ${(q)f})"%% *} &>/dev/null } && { mpv ${f} & disown };
}
