#!/bin/zsh
ping -c 1 1.1.1.1 &>/dev/null || return 1;
typeset omdbapikey OSuser OSpass file;
# --addic7ed Auser Apass --legendastv Luser Lpass;
typeset -a open files;
OSuser=VwAxYImyiMgeaXWXOSkB;
OSpass=HgFdrwvpWYhSfSoHZhKcBQVGvimwRrKopFPNEXqWPEBsakGHXTTHgtoweeVXrnFXipDBICGSJeQzircESKtjPKUyBWZjKPBRyQKDVlIkinPrnSGDigJLYMMhGMwFIoS;
omdbapikey=c62d6dc4;

if ((# == 0)) {
  open=(${(u)${(f)"$( ps -o cmd= -C mpv )"}/(* \/|*)//});
  ((${#open} > 1)) && {
    [[ -t 0 ]] && {
      files=(${(f)"$(fzf -i -m --header='Files to search subs for: ' --reverse --border=horizontal <<< ${(F)files})"}) || return 1;
    } || {
      while { true } { file+=("$(dmenu -p 'Select file to search subs for: ' -l 16 <<< ${(F)files})") || break };
    };
  } || { files=${open[1]} };
} else {
  # files=(${(f)"$(printf '%s\n' ~/mov/**/* | fzf -i -m --header='Files to search subs for: ' --reverse --border=horizontal)"});
  files=(${@:a});
};

for file ( ${files} ) {
  if [[ -f ${files} ]] {
    subliminal \
      --opensubtitles ${OSuser} ${OSpass} \
      --omdb ${omdbapikey} \
      download -l en -hi -d ${file:h} ${(qqq)file};
      { kill ${"$(ps -o pid=,cmd= -C mpv | pcre2grep ${(q)file})"%% *} &>/dev/null } && { mpv ${file} & disown };
  } else { continue };
};
