#!/bin/zsh
[[ -t 0 ]] || return 1;
emulate -LR zsh;
setopt pipe_fail;
while { getopts s n } { case ${n} {
  (s) 
    typeset -a a s; a=(${(fq)"$(printf '%s\n' ~/Downloads/texpkg/**/*(.N) | fzf -i -m --reverse --bind=alt-c:clear-selection,alt-v:select-all,\[:up,\':down)"}); 
    for n ( ${a} ) {
      [[ ${n} =~ '\.pdf$' ]] && { qpdfview --unique --quiet ${n} & disown } || s+=${n};
    }; ((${#s} > 0)) && less ${s}; return 0;;
  (*) return 1;;
}; };

ping -c 1 1.1.1.1 &>/dev/null || return 1;
typeset t base query n;
typeset -i r lr q c p;
typeset -a pkg url file dir;
n=$'\n';
base=https://ctan.org;
t=$(mktemp);
query="${${@}:-$(read -er "?${n}> ")}";
[[ -d ~/Downloads/texpkg ]] || mkdir ~/Downloads/texpkg;

until [[ ${query} =~ '^\s*$' ]] {
  curl -sfLH User-Agent: $(surfraw -p -escape-url-args=yes ctan ${query}) > ${t} || return 3;

  pkg=(${(ps.Package .)"$(pup -p -f ${t} 'div.hit text{}'|tr -d '\n')"});
  url=(${(f)"$(pup -p -f ${t} 'div.hit a attr{href}')"});
  r=${#pkg};
  lr=${(c)#r};

  while { true } {
    c=$(for q ( {1..${r}} ) {
      printf "%.${lr}d  %b%s\n" \
        ${q} \
        '\033[1m' ${pkg[q]};
    } | fzy -l $LINES | cut -f 1 -d ' ') || break;
    ((c > 0 && c <= ${r})) && {
      curl -sfLH User-Agent: ${base}${url[c]} > ${t};
      file+=(${(f)"$(pup -p -f ${t} 'body tr:nth-child(2) a attr{href}' | fzf -i -m --reverse --bind=alt-c:clear-selection,alt-v:select-all,\[:up,\':down)"});
      ((${#file} > p)) && {
        p=$((${#file} - p));
        for q ( {1..${p}} ) { dir+=${pkg[c]} };
      };
    };
  };
  query=$(read -er "?${n}> ");
};

trap 'printf "%s\n" ${file}; return 1' INT HUP;
q=0;
for n ( ${file} ) {
  wget -P ~/Downloads/texpkg/${dir[++q]} ${n};
};

rm ${t};
