#!/bin/zsh
[[ -t 0 ]] || return 1;
emulate -LR zsh;
setopt pipefail;

((# > 0)) || {
  typeset -a a s; a=(${(fq)"$(printf '%s\n' ~/Downloads/texpkg/**/*(.N) | fzf -i -m --reverse --bind=alt-c:clear-selection,alt-v:select-all,\[:up,\':down)"}); 
  for n ( ${a} ) {
    case ${n:e} {
      (pdf) qpdfview --unique --quiet ${n} &;;
      (htm(|l)) sf ${n};;
      ([1-9]) man -l ${n};;
      (jp(|e)g|png|tiff|gif) feh ${n} &;;
      (*) less ${n};;
    };
  };
  disown;
};

ping -c 1 1.1.1.1 &>/dev/null || return 1;
typeset t base query n;
typeset -i r q c p;
typeset -a pkg url file dir;
n=$'\n';
base=https://ctan.org;
t=$(mktemp);
query="${@}";
[[ -d ~/Downloads/texpkg ]] || mkdir ~/Downloads/texpkg;

until [[ ${query} =~ '^\s*$' ]] {
  curl -sfLH User-Agent: -o ${t} $(surfraw -p -escape-url-args=yes ctan ${query}) || { rm -f ${t}; return 3 };

  pkg=(${(ps.Package .)"$(pup -p -f ${t} 'div.hit text{}'|tr -d '\n')"});
  url=(${(f)"$(pup -p -f ${t} 'div.hit a attr{href}')"});
  r=${#pkg};

  while { true } {
    c=$(printf '%s\n' ${pkg} | nl -n ln | fzf -i +m --reverse --bind=\[:up,\':down  | cut -f 1 -d ' ') || break;
    ((c > 0 && c <= ${r})) && {
      curl -sfLH User-Agent: ${base}${url[c]} > ${t};
      file+=(${(f)"$(pup -p -f ${t} 'body tr:nth-child(2) a attr{href}' | fzf -i -m --reverse --bind=alt-c:clear-selection,alt-v:select-all,\[:up,\':down)"});
      ((${#file} > p)) && {
        p=$((${#file} - p));
        for q ( {1..${p}} ) { dir+=${pkg[c]} };
      };
    };
  };
  query=$(read -er "?${n}> ");
};

((${#file} == 0)) || printf '%s\n' 'All URLS:' ${file} ${(l.COLUMNS..-.)};
q=0;
for n ( ${file} ) {
  wget -P ~/Downloads/texpkg/${dir[++q]} ${n};
};

rm -f ${t};
