#!/bin/zsh
typeset s;
typeset -a a;
a=(${(f)"$(printf '%s\n' /opt/texlive/2020/texmf-dist/doc/**/*pdf(.-D) | fzf -i -m --reverse )"});
for s in $a; do;
[[ ! -f $s ]] && continue;
qpdfview --unique --quiet $s &;
done;
