#!/bin/zsh
local a s d f;
a=(
    ryuquezacotl
    yeomanvidya
    gamozo
    mrllamasc
    3moth
    numidium3rd
    naysayer88
);
d=(
    360p
    480p
    720p
    720p60
    1080p60
    best
    worst
)
s=$(dmenu -i <<< ${(F)a}) || return 1;
f=$(dmenu -i <<< ${(F)d}) || return 1;

# mpv -- https://www.twitch.tv/${s}/ & disown; exit;
streamlink -p mpv --title '{title} -- {author} -- {url}' --retry-open 8 https://www.twitch.tv/$s $f & disown; exit;