#!/bin/zsh
emulate -LR zsh;
setopt err_return;

ping -c 1 1.1.1.1 &>/dev/null || return 3;

typeset t q h;
typeset -a file;
typeset -i a;
t=$(mktemp -d);
file=(
  # 01
  http://winhelp2002.mvps.org/hosts.txt
  # 02
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
  # 03
  https://someonewhocares.org/hosts/zero/
  # 04
  https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  # 05
  https://raw.githubusercontent.com/nickspaargaren/pihole-google/master/google-domains
  # 06
  https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt
  # 07
  https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/microsoft/all
  # 08
  https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/facebook/all
  # 09
  https://github.com/nickspaargaren/pihole-google/raw/master/categories/analytics.txt
  # 10
  https://github.com/nickspaargaren/pihole-google/raw/master/categories/android.txt
  # 11
  https://github.com/nickspaargaren/pihole-google/raw/master/categories/dns.txt
  # 12
  https://github.com/nickspaargaren/pihole-google/raw/master/categories/domains.txt
  # 13
  https://github.com/nickspaargaren/pihole-google/raw/master/categories/doubleclick.txt
  # 14
  https://github.com/nickspaargaren/pihole-google/raw/master/categories/firebase.txt
  # 15
  https://github.com/nickspaargaren/pihole-google/raw/master/categories/fonts.txt
  # 16
  https://github.com/nickspaargaren/pihole-google/raw/master/categories/general.txt
  # 17
  https://github.com/nickspaargaren/pihole-google/raw/master/categories/mail.txt
  # 18
  https://github.com/nickspaargaren/pihole-google/raw/master/categories/products.txt
  # 19
  https://github.com/nickspaargaren/pihole-google/raw/master/categories/proxies.txt
  # 20
  https://github.com/nickspaargaren/pihole-google/raw/master/categories/shortlinks.txt
  # 21
  https://github.com/nickspaargaren/pihole-google/raw/master/categories/youtube.txt
  # 22
  https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt
  # 23
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
  # 24
  https://github.com/oneoffdallas/dohservers/raw/master/list.txt
  # 25
  https://github.com/oneoffdallas/dohservers/raw/master/iplist.txt
  # 26
  https://raw.githubusercontent.com/c-edw/ios-telemetry/master/blacklist
  # 27
  https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list/-/raw/master/For%20hosts%20file/The_Quantum_Ad-List.txt  
  # 28
  https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-social/hosts
  # 29
  https://block.energized.pro/ultimate/formats/hosts.txt
  # 30
  https://raw.githubusercontent.com/badmojr/1Hosts/master/complete/hosts.txt
  # 31 torrents too
  https://raw.githubusercontent.com/tankmohit/UnifiedHosts/master/hosts.all
  # 32
  https://raw.githubusercontent.com/nickspaargaren/no-google/master/categories/dns.txt
  # 33
  https://raw.githubusercontent.com/nickspaargaren/no-google/master/categories/fonts.txt
  # 34
  https://raw.githubusercontent.com/nickspaargaren/no-google/master/categories/domains.txt
  # 35
  https://raw.githubusercontent.com/nickspaargaren/no-google/master/categories/products.txt
  # 36
  https://raw.githubusercontent.com/Cybo1927/Hosts/master/Anti/Anti%20Verizon
  # 37
  https://v.firebog.net/hosts/static/HPHosts/Hostsgrm.txt
  # 38
  https://raw.githubusercontent.com/anudeepND/blacklist/master/CoinMiner.txt
  # 39
  https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
  # 40
  https://raw.githubusercontent.com/meinhimmel/hosts/master/hosts
);

for a ( {1..${#file}} ) { wget -q -O ${t}/${a} ${file[a]} & };
printf '%s\n' 'Downloading hosts files.' 'Fucking wait.' ${(l.COLUMNS..-.)}; wait; rm -f ${t}/wget*(.N);

pup -f ${t}/3 -p '.BODY' | tail -n +108 > ${t}/_ && mv ${t}/_ ${t}/3;

# https://unix.stackexchange.com/questions/29724/how-to-properly-collect-an-array-of-lines-in-zsh
perl -ne 's/^#0\.0\.0\.0 (\S+)$/$1/ && print' /etc/hosts >> ~/dcs/hosts/holdme;
sort -uo ~/dcs/hosts/holdme ~/dcs/hosts/holdme;

printf '%s\n' \
  '127.0.0.1 localhost' \
  '127.0.0.1 localhost.localdomain' \
  '127.0.0.1 local' \
  '255.255.255.255 broadcasthost' \
  '::1 localhost' \
  '::1 ip6-localhost' \
  '::1 ip6-loopback' \
  'fe80::1%lo0 localhost' \
  'ff00::0 ip6-localnet' \
  'ff00::0 ip6-mcastprefix' \
  '0.0.0.0 0.0.0.0' > /etc/hosts;

sort -u <(perl -pe '
  s/.*\b((local|broadcast)host|loopback|ip6-\w+)\b.*//n;
  s/[ \t\f\r]+/ /g;
  s/#+/#/g;
  s/^ +//;
  s/^#? ?:+ ?//;
  s/^#\s*0\.0\.0\.0 /0.0.0.0 /n;
  s/^#.*$//;
  s/^(.+)#.*$/$1/;
  s/(^(?!0\.0\.0\.0).+)/0.0.0.0 $1/;
  s/(^0\.0\.0\.0\.)(\S+)/$1 $2/;
  # s/^0\.0\.0\.0 127\.0\.0\.1/0.0.0.0/;
  s/ +$//' ${t}/*(.oc[1,${#file}]) | tr -s '\n') <~/dcs/hosts/blockme > ${t}/_;

# if [[ -s holdme ]] {
#   while IFS= read -r h; do perl -ie "s/^${h}$/#&/" h >> /etc/hosts; done < holdme;
# } else {
#   cat h >> /etc/hosts;
# };
###
# [[ -n $unblock ]] && for file in {1..${#unblock}}; do; perl -ipe "s/(.*\b${unblock[file]}$)/#\1/" h; done;
###
# for q ( ${(f)"$(< ~/dcs/holdme)"} ) { sed -ir "s/^0\.0\.0\.0 ${q}$/#&/" ${t}/h };
###
# diff ${t}/h ~/dcs/holdme | pcre2grep '^<' | cut -c 3- >> /etc/hosts
###
h=${(j:|:)$(<~/dcs/hosts/holdme)};
<<(perl -pe "s/^0\.0\.0\.0 (?:${h})\n//" ${t}/_) <~/dcs/hosts/redirections >> /etc/hosts;
rm -vf ${t}/*;


##########################################################################################

file=(
  https://easylist.to/easylist/easylist.txt
  https://easylist.to/easylist/easyprivacy.txt
  https://easylist.to/easylist/fanboy-social.txt
  https://easylist.to/easylist/fanboy-annoyance.txt
  https://secure.fanboy.co.nz/fanboy-cookiemonster.txt
  http://stanev.org/abp/adblock_bg.txt
  https://easylist.to/easylistgermany/easylistgermany.txt
  https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
);
for a ( {1..${#file}} ) { wget -P ${t} ${file[a]} & };
printf '%s\n' 'Downloading wyebadblock json files.' 'Fucking wait.' ${(l.COLUMNS..-.)}; wait; rm -f ${t}/wget-*(.N);

perl -pe 's/^!.*\n//' ${t}/*(.oc[1,${#file}]) | sort -u | tail -n +3 > ~/.config/wyebadblock/easylist.txt;

rm -rvf ${t};
