#!/bin/zsh
emulate -LR zsh;
ping -c 1 github.com &>/dev/null && ! ps -C uhosts &>/dev/null || return 2;
typeset t;
typeset -a file unblock;
typeset -i a;
t=$(mktemp -d);
file=(
  'http://winhelp2002.mvps.org/hosts.txt'                                                                             #  1
  'https://raw.githubusercontent.com/c-edw/ios-telemetry/master/blacklist'                                            #  2
  'https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/microsoft/all'                            #  3
  'https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt'                                         #  4
  'https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/facebook/all'                             #  5
  'https://github.com/nickspaargaren/pihole-google/raw/master/categories/analytics.txt'                               #  6
  'https://github.com/nickspaargaren/pihole-google/raw/master/categories/android.txt'                                 #  7
  'https://github.com/nickspaargaren/pihole-google/raw/master/categories/dns.txt'                                     #  8
  'https://github.com/nickspaargaren/pihole-google/raw/master/categories/domains.txt'                                 #  9
  'https://github.com/nickspaargaren/pihole-google/raw/master/categories/doubleclick.txt'                             # 10
  'https://github.com/nickspaargaren/pihole-google/raw/master/categories/firebase.txt'                                # 11
  'https://github.com/nickspaargaren/pihole-google/raw/master/categories/fonts.txt'                                   # 12
  'https://github.com/nickspaargaren/pihole-google/raw/master/categories/general.txt'                                 # 13
  'https://github.com/nickspaargaren/pihole-google/raw/master/categories/mail.txt'                                    # 14
  'https://github.com/nickspaargaren/pihole-google/raw/master/categories/products.txt'                                # 15
  'https://github.com/nickspaargaren/pihole-google/raw/master/categories/proxies.txt'                                 # 16
  'https://github.com/nickspaargaren/pihole-google/raw/master/categories/shortlinks.txt'                              # 17
  'https://github.com/nickspaargaren/pihole-google/raw/master/categories/youtube.txt'                                 # 18
  'https://raw.githubusercontent.com/nickspaargaren/pihole-google/master/google-domains'                              # 19
  'https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt'                                # 20
  'https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-social/hosts'              # 21
  'https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt'                                  # 22
  'https://github.com/oneoffdallas/dohservers/raw/master/list.txt'                                                    # 23
  'https://github.com/oneoffdallas/dohservers/raw/master/iplist.txt'                                                  # 24
  'http://someonewhocares.org/hosts/zero/'                                                                            # 25
  'https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list/-/raw/master/For%20hosts%20file/The_Quantum_Ad-List.txt'  # 26
);

for a ( {1..${#file}} ) { wget -O ${t}/${a} ${file[a]} & }; wait;

pup -f ${t}/25 -p '.BODY' | tail -n +99 > ${t}/0 && mv ${t}/0 ${t}/25;

# https://unix.stackexchange.com/questions/29724/how-to-properly-collect-an-array-of-lines-in-zsh
unblock=(${(f)"$(perl -ne 's/^#(?:0\.0\.0\.0|::) //n && print' /etc/hosts)"});
printf '%s\n' $unblock > ~/dcs/holdme;

head -n 29 ${t}/21 | tail -n 14 > /etc/hosts;
sed -i '1,40d' ${t}/21;

cat ${t}/*(N) ~/dcs/blockme | perl -pe '
  s/.*\b((local|broadcast)host|loopback|ip6-\w+)\b.*//n;
  s/[\ \t\f\r]+/ /g;
  s/#+/#/g;
  s/^ //;
  s/^#? ?:+ //;
  s/^# ?(0\.0\.0\.0) /0.0.0.0 /n;
  s/^# ?.*$//;
  s/^#.*$//;
  s/(^(?!0\.0\.0\.0).+)/0.0.0.0 $1/; # negative look-ahead assertion
  s/^0\.0\.0\.0 127\.0\.0\.1/0.0.0.0/;
  #s/(^.{1,6}$|^.{7}(?<!0\.0\.0\.0).*)/0\.0\.0\.0 $1/; # negative look-back assertion
  #s/^([^0]|0($|[^.]|\.($|[^0]|0($|[^.]|\.($|[^0]|0($|[^.]|\.($|[^0]|0($|[^ ])))))))).*/0.0.0.0 $1/; # char set and alternations
  s/ $//;' | tr -s '\n' | sort -u > ${t}/h;

# if [ -s holdme ]; then; 
#   while IFS= read -r h; do perl -ie "s/^${h}$/#&/" h >> /etc/hosts; done < holdme;
# else; cat h >> /etc/hosts; fi;
# [[ -n $unblock ]] && for file in {1..${#unblock}}; do; perl -ipe "s/(.*\b${unblock[file]}$)/#\1/" h; done;
((${#unblock} > 0)) && for a ( {1..${#unblock}} ) { sed -ir "s/.* ${unblock[a]}$/#&/" ${t}/h };
cat ${t}/h >> /etc/hosts && rm -rf ${t};
