#!/bin/sh

# A dmenu binary prompt script.
# Gives a dmenu prompt labeled with $1 to perform command $2.
# For example:
# `./prompt "Do you want to shutdown?" "shutdown -h now"`

[ "$(printf "2 No\\n1 Yes" | dmenu -i -p "$1" -l 2)" = "1 Yes" ] && $2