#!/bin/zsh
for s ( ${@} ) {
   { youtube-dl --quiet --write-auto-sub --skip-download --output '~/mov/%(title)s' ${s} } && {
    a=(~/mov/*.en.vtt(.oc[1]));
    [[ -n ${a} ]] || { printf '%s: No English subtitles found.\n' ${s#*=}; continue };
    sed '/-->/d; /<c>/d; /^[[:space:]]*$/d' ${a} | uniq > ${a%.en.vtt}.txt;
    rm $a &>/dev/null;
  };
};

